FROM ubuntu:18.04

RUN useradd -ms /bin/bash indy

# Install environment

RUN apt-get update -y && apt-get install -y \
	wget \
	python3-pip \
	python-setuptools \
	apt-transport-https \
	ca-certificates

WORKDIR /home/indy

RUN pip3 install -U \
	pip \
	setuptools

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
COPY . /code/

